#!/bin/bash
py_file=$PYFILE; if [ -n "$py_file" ]; then python -m py_compile "$py_file"; output_file="${py_file}c"; echo "Compiled file: $output_file"; else echo "Environment variable PYFILE is not set."; fi
